num1=int(input("enter number-1:"))
num2=int(input("enter number-2:"))
sum=(num1+num2)
diff=(num1-num2)
div=(num1/num2)
pro=(num1*num2)
print(f"Addition {sum},\nSubstraction {diff} ,\nmultipication {pro},\n division {div}")